name: End-to-end tests

on:
  repository_dispatch:
    types: [e2e-command]

permissions:
  contents: read
  pull-requests: write

jobs:
  e2ePR:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: eyes

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Print event 🖨️
        run: |
          echo off
          echo '${{ toJson(github.event.client_payload.slash_command) }}'

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Echo comment
        run: |
          echo "${{ github.event.comment.body }}"

      - name: Extract app names and run e2e tests
        run: |
          APP="${{ github.event.client_payload.slash_command.args.unnamed.arg2 }}"
          PREFIX="/e2e "          
          npx turbo e2e --filter=$APP

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
