name: e2e-on-comment
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "The repository from which the slash command was dispatched"
        required: true
      comment-id:
        description: "The comment-id of the slash command"
        required: true
jobs:
  showParams:
    - name: Output command and arguments
      run: |
        echo ${{ github.event.client_payload.slash_command.command }}
        echo ${{ github.event.client_payload.slash_command.args.all }}
