name: e2e-command
on:
  repository_dispatch:
    types: [e2e-command]
jobs:
  e2ePR:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: eyes

      - name: Print E2E variables
        run: |
          echo ${{ github.event.client_payload.slash_command.command }}
          echo ${{ github.event.client_payload.slash_command.args.all }}

  e2e:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Echo comment
        run: |
          echo "${{ github.event.comment.body }}"

      - name: Extract app names and run e2e tests
        run: |
          COMMENT="${{ github.event.comment.body }}"
          PREFIX="/e2e "
          if [[ "$COMMENT" == $PREFIX* ]]; then
            ARGS=${COMMENT#$PREFIX}
            if [ -z "$ARGS" ]; then
              npx turbo e2e
            else
              for APP in $ARGS; do
                npx turbo e2e --filter=$APP
              done
            fi
          fi
      # - name: Run e2e
      #   uses: peter-evans/slash-command-dispatch@v4
      #   with:
      #     token: ${{ secrets.PAT }}
      #     commands: e2e
      #     dispatch-type: workflow
      #     static-args: |
      #       repository=${{ github.repository }}
      #       comment-id=${{ github.event.comment.id }}

  finish:
    runs-on: ubuntu-latest
    steps:
      - name: Complete with reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          reaction-token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
