name: e2e-pr-command
on:
  repository_dispatch:
    types: [e2e-command]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: e2e
          dispatch-type: workflow
          static_args: |
            "repository=${{ github.repository }}"
            "comment-id=${{ github.event.comment.id }}"
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray
  # helloWorld:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checkout the pull request branch
  #     - uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.PAT }}
  #         repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
  #         ref: ${{ github.event.client_payload.pull_request.head.ref }}

  #     # Append a response to the user that issued the command
  #     - name: Append to hello-world.txt
  #       run: echo "Hello @${{ github.event.client_payload.github.actor }}!" >> hello-world.txt

  #     - name: Add reaction
  #       uses: peter-evans/create-or-update-comment@v4
  #       with:
  #         token: ${{ secrets.PAT }}
  #         repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
  #         comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
  #         reactions: hooray
