name: End-to-end tests

on:
  repository_dispatch:
    types: [run-e2e]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Echo comment
        run: |
          echo "${{ github.event.comment.body }}"

      - name: Extract app names and run e2e tests
        run: |
          COMMENT="${{ github.event.comment.body }}"
          PREFIX="/e2e "
          if [[ "$COMMENT" == $PREFIX* ]]; then
            ARGS=${COMMENT#$PREFIX}
            if [ -z "$ARGS" ]; then
              npx turbo e2e
            else
              for APP in $ARGS; do
                npx turbo e2e --filter=$APP
              done
            fi
          fi
