name: Chat Ops BOT
on:
  issue_comment:
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print event 🖨️
        run: |
          echo off
          echo '${{ toJson(github.event) }}'

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: |
            e2e
          permission: none
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            ref=${{ steps.pr.outputs.branch }}
