name: Slash Command Dispatch
on:
  issue_comment:
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo apps
        run: |
          echo "Apps: ${{ github.event.client_payload.slash_command.args.named.apps }}"
          echo "Apps: ${{ github.event.client_payload.slash_command.args.all }}"

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: |
            e2e
          issue-type: pull-request
          dispatch-type: workflow
          apps: ${{ github.event.client_payload.slash_command.args.all }}
