name: Chat Ops BOT
on:
  issue_comment:
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print event 🖨️
        run: |
          echo off
          echo '${{ toJson(github.event) }}'

      # - name: Find the PR branch name 🔎
      #   uses: bahmutov/get-branch-name-by-pr@v1
      #   id: pr
      #   with:
      #     repo-token: ${{ secrets.PERSONAL_TOKEN }}
      #     pr-id: ${{ github.event.issue.number }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: |
            e2e
          issue-type: pull-request
          dispatch-type: workflow
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            ref=${{ steps.pr.outputs.branch }}
