name: Slash Command Dispatch
on:
  issue_comment:
    # Type "edited" added here for test purposes. Where possible, avoid
    # using to prevent processing unnecessary events.
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      # Checkout is necessary here due to referencing a local action.
      # It's also necessary when using the 'config-from-file' option.
      # Otherwise, avoid using checkout to keep this workflow fast.
      - uses: actions/checkout@v4

      # Basic configuration
      # - name: Slash Command Dispatch
      #   uses: ./
      #   with:
      #     token: ${{ secrets.PAT }}
      #     commands: |
      #       hello-world-local
      #       ping-local
      #     permission: none
      #     issue-type: issue

      # Advanced JSON configuration
      - name: Slash Command Dispatch (JSON)
        id: scd
        uses: ./
        with:
          token: ${{ secrets.PAT }}
          config: >
            [
              {
                "command": "fix-pr",
                "permission": "write",
                "issue_type": "pull-request",
              }
            ]

      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}

      # Advanced JSON configuration from file
      # (These commands do not do anything and are just a reference example)
      - name: Slash Command Dispatch (JSON file)
        uses: ./
        with:
          token: ${{ secrets.PAT }}
          reactions: false
          config-from-file: .github/slash-command-dispatch.json
